import type { RequirementTemplate } from "./types.js";

export const MANUFACTURING_REQUIREMENT_LIBRARY: readonly RequirementTemplate[] = [
  {
    id: "mfg.site.minimum-acreage",
    name: "Minimum Site Acreage",
    facilityType: "MANUFACTURING",
    categoryId: "real_estate.site",
    metricKey: "metric.site.available_acres",
    defaultClassification: "MANDATORY",
    defaultOperator: "GTE",
    defaultUnit: "ACRE",
    defaultGeographyLevel: "PROPERTY",
    description: "Available site acreage required to accommodate the project and planned development envelope.",
  },
  {
    id: "mfg.utility.electric-capacity",
    name: "Available Electric Capacity",
    facilityType: "MANUFACTURING",
    categoryId: "infrastructure.electric",
    metricKey: "metric.electric_capacity_available",
    defaultClassification: "MANDATORY",
    defaultOperator: "GTE",
    defaultUnit: "MW",
    defaultGeographyLevel: "PROPERTY",
    description: "Verified electric capacity available to the candidate property.",
  },
  {
    id: "mfg.utility.water-capacity",
    name: "Available Water Capacity",
    facilityType: "MANUFACTURING",
    categoryId: "infrastructure.water",
    metricKey: "metric.water_capacity_available",
    defaultClassification: "MANDATORY",
    defaultOperator: "GTE",
    defaultUnit: "GPD",
    defaultGeographyLevel: "PROPERTY",
    description: "Available water-system capacity at the candidate property.",
  },
  {
    id: "mfg.utility.wastewater-capacity",
    name: "Available Wastewater Capacity",
    facilityType: "MANUFACTURING",
    categoryId: "infrastructure.wastewater",
    metricKey: "metric.wastewater_capacity_available",
    defaultClassification: "MANDATORY",
    defaultOperator: "GTE",
    defaultUnit: "GPD",
    defaultGeographyLevel: "PROPERTY",
    description: "Available wastewater-system capacity at the candidate property.",
  },
  {
    id: "mfg.logistics.interstate-drive-time",
    name: "Interstate Drive Time",
    facilityType: "MANUFACTURING",
    categoryId: "logistics.interstate",
    metricKey: "metric.interstate_drive_time",
    defaultClassification: "PREFERRED",
    defaultOperator: "WITHIN_DRIVE_TIME",
    defaultUnit: "MINUTE",
    defaultGeographyLevel: "PROPERTY",
    description: "Drive time from the candidate property to the nearest qualifying interstate access point.",
  },
  {
    id: "mfg.logistics.airport-drive-time",
    name: "Commercial Airport Drive Time",
    facilityType: "MANUFACTURING",
    categoryId: "logistics.airport",
    metricKey: "metric.commercial_airport_drive_time",
    defaultClassification: "PREFERRED",
    defaultOperator: "WITHIN_DRIVE_TIME",
    defaultUnit: "MINUTE",
    defaultGeographyLevel: "PROPERTY",
    description: "Drive time from the candidate property to the designated commercial-service airport class.",
  },
] as const;
