import type { MetricDefinition } from "./model.js";

export const METRICS = {
  populationTotal: "metric.population_total",
  populationGrowth5yr: "metric.population_growth_5yr",
  medianHouseholdIncome: "metric.median_household_income",
  laborForceTotal: "metric.labor_force_total",
  laborForceParticipation: "metric.labor_force_participation",
  unemploymentRate: "metric.unemployment_rate",
  establishmentsTotal: "metric.business_establishments_total",
  industryEmployment: "metric.industry_employment",
  industryLocationQuotient: "metric.industry_location_quotient",
  occupationEmployment: "metric.occupation_employment",
  occupationMedianWage: "metric.occupation_median_wage",
  occupationWageP10: "metric.occupation_wage_p10",
  occupationWageP25: "metric.occupation_wage_p25",
  occupationWageP75: "metric.occupation_wage_p75",
  occupationWageP90: "metric.occupation_wage_p90",
  occupationWageGrowth: "metric.occupation_wage_growth",
  occupationEmploymentGrowth: "metric.occupation_employment_growth",
  occupationLocationQuotient: "metric.occupation_location_quotient",
  occupationJobPostings: "metric.occupation_job_postings",
  educationCompletions: "metric.education_completions",
  employerCountRelevant: "metric.employer_count_relevant",
  interstateDriveTime: "metric.interstate_drive_time",
  airportDriveTime: "metric.airport_drive_time",
  portDriveTime: "metric.port_drive_time",
  electricRateIndustrial: "metric.electric_rate_industrial",
  electricCapacityIndicator: "metric.electric_capacity_indicator",
  utilityUpgradeLeadTime: "metric.utility_upgrade_lead_time",
  propertyTaxRate: "metric.property_tax_rate",
  unionizationRate: "metric.unionization_rate",
  permitProcessingDays: "metric.permit_processing_days",
  housingCostIndex: "metric.housing_cost_index",
  costOfLivingIndex: "metric.cost_of_living_index"
} as const;

const percentMetric = (id: string, label: string, domain: MetricDefinition["domain"], freshnessDays = 365): MetricDefinition => ({
  id,
  label,
  domain,
  unit: "percent",
  valueType: "number",
  aggregation: "WEIGHTED_AVERAGE",
  freshnessDays
});

export const CATEGORY6_METRIC_DEFINITIONS: readonly MetricDefinition[] = [
  { id: METRICS.populationTotal, label: "Population", domain: "market", unit: "people", valueType: "number", aggregation: "SUM", freshnessDays: 730 },
  percentMetric(METRICS.populationGrowth5yr, "Five-year population growth", "market", 730),
  { id: METRICS.medianHouseholdIncome, label: "Median household income", domain: "market", unit: "USD/year", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 730 },
  { id: METRICS.laborForceTotal, label: "Civilian labor force", domain: "workforce", unit: "workers", valueType: "number", aggregation: "SUM", freshnessDays: 365 },
  percentMetric(METRICS.laborForceParticipation, "Labor-force participation", "workforce"),
  percentMetric(METRICS.unemploymentRate, "Unemployment rate", "workforce", 120),
  { id: METRICS.establishmentsTotal, label: "Business establishments", domain: "market", unit: "establishments", valueType: "number", aggregation: "SUM", freshnessDays: 365 },
  { id: METRICS.industryEmployment, label: "Industry employment", domain: "market", unit: "workers", valueType: "number", aggregation: "SUM", freshnessDays: 365 },
  { id: METRICS.industryLocationQuotient, label: "Industry location quotient", domain: "market", unit: "ratio", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.occupationEmployment, label: "Occupational employment", domain: "workforce", unit: "workers", valueType: "number", aggregation: "SUM", freshnessDays: 365 },
  { id: METRICS.occupationMedianWage, label: "Occupational median wage", domain: "workforce", unit: "USD/hour", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.occupationWageP10, label: "Occupational 10th-percentile wage", domain: "workforce", unit: "USD/hour", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.occupationWageP25, label: "Occupational 25th-percentile wage", domain: "workforce", unit: "USD/hour", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.occupationWageP75, label: "Occupational 75th-percentile wage", domain: "workforce", unit: "USD/hour", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.occupationWageP90, label: "Occupational 90th-percentile wage", domain: "workforce", unit: "USD/hour", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  percentMetric(METRICS.occupationWageGrowth, "Occupational wage growth", "workforce"),
  percentMetric(METRICS.occupationEmploymentGrowth, "Occupational employment growth", "workforce"),
  { id: METRICS.occupationLocationQuotient, label: "Occupational location quotient", domain: "workforce", unit: "ratio", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.occupationJobPostings, label: "Occupational job postings", domain: "workforce", unit: "postings", valueType: "number", aggregation: "SUM", freshnessDays: 60 },
  { id: METRICS.educationCompletions, label: "Relevant education completions", domain: "education", unit: "completions/year", valueType: "number", aggregation: "SUM", freshnessDays: 730 },
  { id: METRICS.employerCountRelevant, label: "Relevant employer count", domain: "employer", unit: "employers", valueType: "number", aggregation: "SUM", freshnessDays: 180 },
  { id: METRICS.interstateDriveTime, label: "Interstate drive time", domain: "transportation", unit: "minutes", valueType: "number", aggregation: "NONE", freshnessDays: 3650 },
  { id: METRICS.airportDriveTime, label: "Airport drive time", domain: "transportation", unit: "minutes", valueType: "number", aggregation: "NONE", freshnessDays: 3650 },
  { id: METRICS.portDriveTime, label: "Port drive time", domain: "transportation", unit: "minutes", valueType: "number", aggregation: "NONE", freshnessDays: 3650 },
  { id: METRICS.electricRateIndustrial, label: "Industrial electricity rate", domain: "utility", unit: "USD/kWh", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.electricCapacityIndicator, label: "Electric capacity indicator", domain: "utility", unit: "MW", valueType: "number", aggregation: "NONE", freshnessDays: 180 },
  { id: METRICS.utilityUpgradeLeadTime, label: "Utility upgrade lead time", domain: "utility", unit: "months", valueType: "number", aggregation: "NONE", freshnessDays: 180 },
  { id: METRICS.propertyTaxRate, label: "Property tax rate", domain: "business_climate", unit: "percent", valueType: "number", aggregation: "NONE", freshnessDays: 365 },
  percentMetric(METRICS.unionizationRate, "Unionization rate", "business_climate"),
  { id: METRICS.permitProcessingDays, label: "Permit processing time", domain: "business_climate", unit: "days", valueType: "number", aggregation: "AVERAGE", freshnessDays: 365 },
  { id: METRICS.housingCostIndex, label: "Housing cost index", domain: "quality_of_life", unit: "index", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 },
  { id: METRICS.costOfLivingIndex, label: "Cost of living index", domain: "quality_of_life", unit: "index", valueType: "number", aggregation: "WEIGHTED_AVERAGE", freshnessDays: 365 }
];
